### ISSUE TITLE
Pause is not working

### ISSUE THREAD

**Issue by softy2k** [kvsur/openai-speech-stream-player#1]
Hello and thanks for this library.
I use this library together with VueJS 3 and it works quite well.

However, the **`pause()`** function does not work correctly, it is a small mistake in the code.
In the code you wrote:
```
    pause() {
        this.audio && !this.audio.paused && this.audio.play();
    }
```
Correct would be:
```
    pause() {
        this.audio && !this.audio.paused && this.audio.pause();
    }
```

In addition to that, the` pause()` function can only be active after `Fetch API` finished.
Basically, you call the function in vain, you have to wait for the completion of the `Fetch stream`.

**Comment by kvsur** [comment]
@softy2k , I'm sorry for only seeing this Issue now. I will fix this problem in the next version, thank you for your suggestion.

**Comment by kvsur** [comment]
@softy2k https://github.com/kvsur/openai-speech-stream-player/releases/tag/1.0.8
